# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

weight_cpp <- function(xx, h) {
    .Call(`_MDCcure_weight_cpp`, xx, h)
}

beran_cpp <- function(data, w) {
    .Call(`_MDCcure_beran_cpp`, data, w)
}

beranT_cpp <- function(data, w) {
    .Call(`_MDCcure_beranT_cpp`, data, w)
}

beranC_cpp <- function(data, w) {
    .Call(`_MDCcure_beranC_cpp`, data, w)
}

latency_estimator_multivariate_cpp <- function(t, x, T, X, delta, H_in = NULL) {
    .Call(`_MDCcure_latency_estimator_multivariate_cpp`, t, x, T, X, delta, H_in)
}

mdc_cpp <- function(X_, Y_, center) {
    .Call(`_MDCcure_mdc_cpp`, X_, Y_, center)
}

mdd_cpp <- function(X, Y, center) {
    .Call(`_MDCcure_mdd_cpp`, X, Y, center)
}

permutation_test_cpp_parallel <- function(X, Y, n_permutations, center, parallel, n_threads) {
    .Call(`_MDCcure_permutation_test_cpp_parallel`, X, Y, n_permutations, center, parallel, n_threads)
}

pmdc_cpp <- function(X, Y, Z) {
    .Call(`_MDCcure_pmdc_cpp`, X, Y, Z)
}

pmdd_cpp <- function(X, Y, Z) {
    .Call(`_MDCcure_pmdd_cpp`, X, Y, Z)
}

